<?php

declare(strict_types=1);

// phpcs:disable PSR1.Classes.ClassDeclaration.MissingNamespace

use Phinx\Migration\AbstractMigration;

final class V20250303092857 extends AbstractMigration
{
  public function change(): void
  {
    $defaults = [
      'App\Models\Alert'                            => [1, 255, 2, 3, 10],
      'App\Models\Appliance'                        => [1, 32, 23, 11, 12, 13],
      'App\Models\Applianceenvironment'             => [1],
      'App\Models\Appliancetype'                    => [1],
      'App\Models\Authldap'                         => [1, 30, 3, 7],
      'App\Models\Authsso'                          => [1, 4, 5],
      'App\Models\Autoupdatesystem'                 => [1],
      'App\Models\Blacklist'                        => [1, 12, 11],
      'App\Models\Blacklistedmailcontent'           => [1],
      'App\Models\Budget'                           => [1, 4, 7, 5, 6],
      'App\Models\Budgettype'                       => [1],
      'App\Models\Businesscriticity'                => [1, 13],
      'App\Models\Calendar'                         => [1],
      'App\Models\Cartridgeitem'                    => [1, 4, 34, 23, 3],
      'App\Models\Cartridgeitemtype'                => [1],
      'App\Models\Category'                         => [14, 13, 3, 74, 75, 76, 85],
      'App\Models\Certificate'                      => [1, 31, 7, 23, 10],
      'App\Models\Certificatetype'                  => [1],
      'App\Models\Change'                           => [1, 12, 3, 7, 15],
      'App\Models\Cluster'                          => [1, 31, 4, 200],
      'App\Models\Clustertype'                      => [1],
      'App\Models\Computer'                         => [2, 31, 4, 23, 40, 5],
      'App\Models\Computerantivirus'                => [1, 2, 6, 3, 4],
      'App\Models\Computermodel'                    => [1, 130, 134, 135, 136],
      'App\Models\Computertype'                     => [1],
      'App\Models\Consumableitem'                   => [1, 4, 34, 23, 3],
      'App\Models\Consumableitemtype'               => [1],
      'App\Models\Contact'                          => [1, 11, 119, 9, 84, 85, 87],
      'App\Models\Contacttype'                      => [1],
      'App\Models\Contract'                         => [1, 31, 4, 3],
      'App\Models\Contracttype'                     => [1],
      'App\Models\Crontask'                         => [1, 4, 5, 6, 7],
      'App\Models\Datacenter'                       => [1, 3],
      'App\Models\Dcroom'                           => [1, 2, 3],
      'App\Models\Devicebattery'                    => [1, 13, 23, 11],
      'App\Models\Devicebatterytype'                => [1],
      'App\Models\Devicecase'                       => [1, 12, 23, 13],
      'App\Models\Devicecasemodel'                  => [1],
      'App\Models\Devicecasetype'                   => [1],
      'App\Models\Devicecontrol'                    => [1, 13, 14, 15, 12],
      'App\Models\Devicecontrolmodel'               => [1],
      'App\Models\Devicedrive'                      => [1, 3, 14, 15, 12, 13],
      'App\Models\Devicedrivemodel'                 => [1],
      'App\Models\Devicefirmware'                   => [1, 13, 23, 12, 14, 11],
      'App\Models\Devicefirmwaremodel'              => [1],
      'App\Models\Devicefirmwaretype'               => [1],
      'App\Models\Devicegeneric'                    => [1, 13, 23],
      'App\Models\Devicegenericmodel'               => [1],
      'App\Models\Devicegenerictype'                => [1],
      'App\Models\Devicegraphiccard'                => [1, 23, 11, 14, 15, 12],
      'App\Models\Devicegraphiccardmodel'           => [1],
      'App\Models\Deviceharddrive'                  => [1, 3, 15, 14, 11, 12, 13],
      'App\Models\Deviceharddrivemodel'             => [1],
      'App\Models\Devicememory'                     => [1, 13, 14, 23, 12, 11],
      'App\Models\Devicememorymodel'                => [1],
      'App\Models\Devicememorytype'                 => [1],
      'App\Models\Devicemotherboard'                => [1, 23, 15, 11],
      'App\Models\Devicemotherboardmodel'           => [1],
      'App\Models\Devicenetworkcard'                => [1, 23, 13, 12],
      'App\Models\Devicenetworkcardmodel'           => [1],
      'App\Models\Devicepci'                        => [1, 3, 15],
      'App\Models\Devicepcimodel'                   => [1],
      'App\Models\Devicepowersupply'                => [1, 13, 23, 12, 11],
      'App\Models\Devicepowersupplymodel'           => [1],
      'App\Models\Deviceprocessor'                  => [1, 3, 15, 12, 13, 14],
      'App\Models\Deviceprocessormodel'             => [1],
      'App\Models\Devicesensor'                     => [1, 12, 23],
      'App\Models\Devicesensormodel'                => [1],
      'App\Models\Devicesensortype'                 => [1],
      'App\Models\Devicesimcard'                    => [1, 13, 23, 12, 14],
      'App\Models\Devicesimcardtype'                => [1],
      'App\Models\Devicesoundcard'                  => [1, 12, 23, 13],
      'App\Models\Devicesoundcardmodel'             => [1],
      'App\Models\Document'                         => [1, 7, 3, 5],
      'App\Models\Documentcategory'                 => [1, 13],
      'App\Models\Documenttype'                     => [1, 3, 4, 5],
      'App\Models\Domain'                           => [1, 2, 6],
      'App\Models\Domainrecordtype'                 => [1],
      'App\Models\Domainrelation'                   => [1],
      'App\Models\Domaintype'                       => [1],
      'App\Models\Enclosure'                        => [1, 31, 40, 5],
      'App\Models\Enclosuremodel'                   => [1],
      'App\Models\Entity'                           => [1, 16],
      'App\Models\Event'                            => [10, 11, 12, 13, 14],
      'App\Models\Fieldblacklist'                   => [1, 4, 6, 7],
      'App\Models\Fieldunicity'                     => [1, 30, 4, 5, 6],
      'App\Models\Filesystem'                       => [1],
      'App\Models\Followuptemplate'                 => [1, 5, 6],
      'App\Models\Fqdn'                             => [1, 12],
      'App\Models\Group'                            => [14, 13, 11, 212, 12, 20],
      'App\Models\Holiday'                          => [1, 11, 12, 13],
      'App\Models\Interfacetype'                    => [1],
      'App\Models\Ipnetwork'                        => [1, 11, 12, 17, 18],
      'App\Models\Knowbaseitemcategory'             => [14, 13],
      'App\Models\Line'                             => [1, 4, 31, 184, 185, 186],
      'App\Models\Lineoperator'                     => [1, 11, 12],
      'App\Models\Linetype'                         => [1],
      'App\Models\Link'                             => [1, 3, 103],
      'App\Models\Location'                         => [14, 13, 12, 15, 18, 105],
      'App\Models\Mailcollector'                    => [1, 2, 22, 302, 301],
      'App\Models\Manufacturer'                     => [1],
      'App\Models\Monitor'                          => [2, 31, 4, 23, 40, 11, 5],
      'App\Models\Monitormodel'                     => [1],
      'App\Models\Monitortype'                      => [1],
      'App\Models\Netpoint'                         => [2, 3],
      'App\Models\Network'                          => [1],
      'App\Models\Networkequipment'                 => [2, 31, 4, 23, 32, 40, 5],
      'App\Models\Networkequipmentmodel'            => [1],
      'App\Models\Networkequipmenttype'             => [1],
      'App\Models\Networkinterface'                 => [1],
      'App\Models\Networkname'                      => [1, 12],
      'App\Models\Notification'                     => [1, 6, 5, 206],
      'App\Models\Notificationtemplate'             => [1, 4],
      'App\Models\Notificationtemplatetranslation'  => [1, 2],
      'App\Models\Operatingsystem'                  => [1],
      'App\Models\Operatingsystemarchitecture'      => [1],
      'App\Models\Operatingsystemedition'           => [1],
      'App\Models\Operatingsystemkernel'            => [1],
      'App\Models\Operatingsystemkernelversion'     => [1, 3],
      'App\Models\Operatingsystemservicepack'       => [1],
      'App\Models\Operatingsystemversion'           => [1, 1001],
      'App\Models\Passivedcequipment'               => [2, 31, 4, 23, 40, 5],
      'App\Models\Passivedcequipmentmodel'          => [1],
      'App\Models\Passivedcequipmenttype'           => [1],
      'App\Models\Pdu'                              => [2, 31, 4, 23, 40, 5],
      'App\Models\Pdumodel'                         => [1],
      'App\Models\Pdutype'                          => [1],
      'App\Models\Peripheral'                       => [2, 31, 4, 23, 11, 40, 5],
      'App\Models\Peripheralmodel'                  => [1],
      'App\Models\Peripheraltype'                   => [1],
      'App\Models\Phone'                            => [2, 31, 4, 23, 40, 5, 9],
      'App\Models\Phonemodel'                       => [1],
      'App\Models\Phonepowersupply'                 => [1],
      'App\Models\Phonetype'                        => [1],
      'App\Models\Planningeventcategory'            => [1, 201],
      'App\Models\Planningexternaleventtemplate'    => [1, 4, 5],
      'App\Models\Plug'                             => [1],
      'App\Models\Printer'                          => [2, 31, 4, 23, 40, 5, 3],
      'App\Models\Printermodel'                     => [1],
      'App\Models\Printertype'                      => [1],
      'App\Models\Problem'                          => [1, 12, 3, 7, 15],
      'App\Models\Problemtemplate'                  => [1],
      'App\Models\Profile'                          => [1, 5, 3, 118],
      'App\Models\Project'                          => [1, 12, 14, 4, 15, 7, 8],
      'App\Models\Projectstate'                     => [1, 12, 11],
      'App\Models\Projecttask'                      => [1, 2, 3, 4, 5, 7, 8],
      'App\Models\Projecttasktemplate'              => [1, 4, 5, 6, 8, 7, 9],
      'App\Models\Projecttasktype'                  => [1],
      'App\Models\Projecttype'                      => [1],
      'App\Models\Queuednotification'               => [1, 20, 14, 22, 16, 15, 7],
      'App\Models\Rack'                             => [2, 31, 4, 23, 8, 40, 5],
      'App\Models\Rackmodel'                        => [1],
      'App\Models\Racktype'                         => [1],
      'App\Models\Reminder'                         => [1, 32, 7, 2],
      'App\Models\Requesttype'                      => [1, 8],
      'App\Models\Rssfeed'                          => [1, 3, 4, 6, 2, 5],
      'App\Models\Rule'                             => [1, 8, 5, 3],
      'App\Models\Ruleaction'                       => [1001, 1002, 1103, 1004],
      'App\Models\Rulecriterium'                    => [1001, 1002, 1103, 1004],
      'App\Models\Rulerightparameter'               => [1, 11],
      'App\Models\Savedsearch'                      => [1, 4, 3, 10],
      'App\Models\Slm'                              => [1, 4],
      'App\Models\Software'                         => [1, 62, 23, 63],
      'App\Models\Softwarecategory'                 => [1, 12],
      'App\Models\Softwarelicense'                  => [1, 10, 5, 4, 8, 9, 168],
      'App\Models\Softwarelicensetype'              => [1, 13],
      'App\Models\Softwareversion'                  => [1, 10, 12, 11],
      'App\Models\Solutiontemplate'                 => [14, 3],
      'App\Models\Solutiontype'                     => [1],
      'App\Models\Ssovariable'                      => [1],
      'App\Models\State'                            => [14, 13],
      'App\Models\Supplier'                         => [1, 9, 3, 11, 13, 4, 6],
      'App\Models\Suppliertype'                     => [1],
      'App\Models\Ticket'                           => [1, 14, 12, 7, 3, 18, 82, 4],
      'App\Models\Ticketrecurrent'                  => [1, 11, 13, 17],
      'App\Models\Tickettemplate'                   => [1],
      'App\Models\User'                             => [1, 400, 8, 3, 79, 14],
      'App\Models\Usercategory'                     => [1],
      'App\Models\Usertitle'                        => [1],
      'App\Models\Virtualmachinestate'              => [1],
      'App\Models\Virtualmachinesystem'             => [1],
      'App\Models\Virtualmachinetype'               => [1],
      'App\Models\Vlan'                             => [1, 11],
      'App\Models\Wifinetwork'                      => [1, 12, 10],
      'App\Models\Form\Form'                        => [1, 4, 5, 9],
      'App\Models\Form\Question'                    => [1, 4],
      'App\Models\Form\Section'                     => [1],
    ];

    foreach ($defaults as $modelName => $nums)
    {
      // Check if not have preference for item and user_id = 0
      $stmt = $this->query('SELECT * FROM displaypreferences where itemtype=? and user_id=0', [$modelName]);
      $rows = $stmt->fetchAll();

      // if not have, create them with default num
      if (count($rows) == 0)
      {
        $rank = 1;
        foreach ($nums as $num)
        {
          $this->execute(
            "INSERT INTO displaypreferences (`itemtype`, `num`, `rank`) VALUES (?, ?, ?)",
            [$modelName, $num, $rank]
          );
          $rank += 1;
        }
      }
    }
  }
}
